### ISSUE TITLE
CSV parsing fails on nil keys

### ISSUE THREAD

**Issue by baarkerlounger** [ankane/rover#12]
Given a CSV with column headers and with empty columns, Rover throws an error on reading CSV:

```
Rover.read_csv("test.csv")
/home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover/data_frame.rb:451:in `check_key': Key must be a string or symbol, got nil (ArgumentError)
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover/data_frame.rb:54:in `block in initialize'
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover/data_frame.rb:53:in `each_key'
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover/data_frame.rb:53:in `initialize'
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover.rb:41:in `new'
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover.rb:41:in `csv_to_df'
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.5/lib/rover.rb:14:in `read_csv'
	from (irb):2:in `<main>'
	from /home/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /home/.rbenv/versions/3.0.2/bin/irb:23:in `load'
	from /home/.rbenv/versions/3.0.2/bin/irb:23:in `<main>'
```

[test.csv](https://github.com/ankane/rover/files/7243196/test.csv)

Ideally Rover would create the DataFrame successfully and just omit any columns that are totally nil, or add a default column header if the column has data but no header.

**Comment by ankane** [comment]
Hey @baarkerlounger, thanks for the suggestion! Added default naming in the commit above.
